### ISSUE TITLE
Ошибка Service 'php' failed to build при запуске контейнера

### ISSUE THREAD

**Issue by alexsoin** [reptily/openserver#5]
Склонировал репозиторий, перешел в каталог bin, запустил команду `./start` после чего отваливается запуск на следующем шаге:
```
Step 13/22 : RUN pecl install memcache && docker-php-ext-enable memcache
 ---> Running in a313db54b0c6
pecl/memcache requires PHP (version >= 8.0.0), installed version is 7.4.13
No valid packages found
install failed
ERROR: Service 'php' failed to build: The command '/bin/sh -c pecl install memcache && docker-php-ext-enable memcache' returned a non-zero code: 1
```
---
OS: Ubuntu 20.04

**Comment by reptily** [comment]
Примерно понял из-за чего ошибка появилась, скоро фикс сделаю

**Comment by reptily** [comment]
> Склонировал репозиторий, перешел в каталог bin, запустил команду `./start` после чего отваливается запуск на следующем шаге:
> 
> ```
> Step 13/22 : RUN pecl install memcache && docker-php-ext-enable memcache
>  ---> Running in a313db54b0c6
> pecl/memcache requires PHP (version >= 8.0.0), installed version is 7.4.13
> No valid packages found
> install failed
> ERROR: Service 'php' failed to build: The command '/bin/sh -c pecl install memcache && docker-php-ext-enable memcache' returned a non-zero code: 1
> ```
> 
> OS: Ubuntu 20.04

Примерно понял из-за чего ошибка появилась, скоро фикс сделаю

**Comment by reptily** [comment]
https://github.com/reptily/openserver/releases/tag/1.0.1

**Comment by alexsoin** [comment]
Спасибо! Теперь всё работает =)
